#!/usr/bin/env ruby
# -*- mode: ruby; coding: utf-8 -*-

BEGIN {
  $LOAD_PATH.push File.dirname($0)
}

require 'TransitionTask'
require 'ConstVars'
require 'fileutils'

begin
  user = ENV['USER']
  group = `id -gn #{user}`.chop

  TransitionTask.new(user, group).execute

  # ensure 32bit binary for leopard environment
  leopard = `uname -r`.chop[/^9./]

  if leopard then
    bundle32bit = '/tmp/AquaSKK.32bit'

    system('lipo', ConstVars::BUNDLE_EXE,
           '-remove', 'x86_64', '-output', bundle32bit);

    if File.exist?(bundle32bit) then
      FileUtils.copy_file(bundle32bit, ConstVars::BUNDLE_EXE)
    end
  end
end
